config/routes.rb
Lawdingo::Application.routes.draw do
  match 'sitemap.xml' => 'sitemaps#sitemap'

  resources :appointments, :only => [:create]

  resources :clients, :only => [:new, :create]

  namespace :framey do
    resources :videos
  end
  post "framey/callback" => "framey/videos#callback"

  resources :lawyers, :only => [:new, :create]
  match '/apply' => "lawyers#new", :as => :new_lawyer

  resources :questions
  resources :reviews
  resources :schools
  resources :inquiries, only: :show
  resources :bids, only: :create
  get "password_resets/new"

  match 'attorneys/:id/call-payment' => 'attorneys#call_payment', 
    as: :call_payment
  match 'attorneys/:id/*slug' => 'attorneys#show', as: :attorney
  match '/paid' => "stripe#subscribe_lawyer", :as => :subscribe_lawyer
  
  resources :users do
    resources :daily_hours, :only => [:index] do
      collection do
        put "update"
      end
    end
    
    resources :offerings, shallow: true

    put 'image_upload'
    get 'chat_session'
    get 'onlinestatus'
  end

  resources :sessions
  resources :password_resets
  resources :conversations do
    get 'review'
    get 'summary'
  end
  match 'conversations/:conversation_id/summary(/:form)' => "conversations#summary", as: :conversation_summary

  namespace :admin do
    resources :questions, only: [:index, :show] do
      post "send_inquiry", on: :collection
    end
    resources :clients
    resources :lawyers do
      get 'account_approval'
      get 'hm_image'
    end
    resources :clsessions
    resources :pages
    resources :homepage_images
    resources :practice_areas
  end

  match 'modparam' =>'users#update_parameter', :as =>:update_parameter
  match "/users/create_lawyer_request", to: "users#create_lawyer_request", as: :create_lawyer_request
  match '/user/sessions/:user_id' =>"users#session_history", :as =>:user_session_history
  match '/users/:user_id/daily_hours' =>"users#daily_hours", :as =>:user_daily_hours
  match '/users/:user_id' =>"users#account_information", :as =>:user_account_information
  match '/about' =>"pages#show", :name =>'about', :as =>:about_page
  match '/about_attorneys' =>"pages#about_attorneys", :name =>'about_attorneys', :as =>:about_attorneys
  match '/terms' =>"pages#terms_of_use", :name =>'terms', :as =>:terms_page
  match '/pricing_process' =>"pages#pricing_process", :name =>'pricing_process', :as =>:pricing_process
  match '/pricing_process_activation' =>"pages#pricing_process_activation", :name =>'pricing_process_activation', :as =>:pricing_process_activation
  match '/process_signup' =>"pages#process_signup", :name =>'process_signup', :as =>:process_signup
  
  match '/login' => "sessions#new", :as => :login
  match '/logout' => "sessions#destroy", :as => :logout
  match '/details' => 'users#payment_info', :as => :card_detail
  match '/welcome' => 'users#welcome_lawyer', :as => :welcome
  match '/Register' => 'users#register_for_videochat', :as => :register_videochat
  match '/find_friend' => 'users#find_remote_user_for_videochat', :as => :find_remote_user
  match '/UpdateBusyStatus' => 'users#update_busy_status', :as => :UpdateBusyStatus
  match '/ScheduleSession' => 'users#send_email_to_lawyer', :as => :schedule_session
  match '/UpdateOnlineStatus' => 'users#update_online_status', :as => :UpdateOnlineStatus
  match '/twilio/phonecall' => 'users#start_phone_call', :as => :phonecall
  match '/twilio/createcall' => 'users#create_phone_call', :as => :create_call
  match '/twilio/endcall' => 'users#end_phone_call', :as => :endcall
  match '/twilio/voice' => 'twilio#twilio_return_voice', :as => :twilio_voice
  match '/twilio/process_gather' => 'twilio#process_gather', :as => :process_gather
  match '/twilio/fallback' => 'twilio#fallback', :as => :twilio_fallback
  match '/twilio/callback' => 'twilio#callbackstatus', :as => :twilio_callback
  match '/twilio/dial_callback' => 'twilio#dial_callback', :as =>:dial_callback
  match '/search' => 'users#search'
  match '/search/populate_specialities' => 'search#populate_specialities'
  match '/search/populate_specialities_next' => 'search#populate_specialities_next'
  match '/search/filter_results' => 'search#filter_results'
  match '/search/carsousel_images' =>'search#get_homepage_lawyers'
  match '/updatePaymentInfo' => 'users#update_payment_info'
  match '/CheckPaymentInfo' => 'users#has_payment_info'
  match '/CheckCallStatus' => 'users#check_call_status'
  match '/UpdateCallStatus' => 'users#update_call_status'

  match '/admin' =>"users#show", :as =>:admin_home
  
  match '/lawyers/:service_type(/:state)' => 'users#home'
  match '/lawyers/:service_type/:state(/:practice_area)' => 'users#home'
  match '/lawyers/:service_type/:state/:practice_area(/:practice_subarea)' => 'users#home'
  match '/auto-detect/detect-state' => 'users#detect_state'
  match '/lawyers' => 'users#home'
  match '/learnmore' => 'users#learnmore'
  root :to => 'users#landing_page'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

  match '/LoginByApp' => 'sessions#login_by_app'
  match '/UpdateOnlineByApp' => 'sessions#set_status_by_app'
end

app/models/client.rb
class Client < User

  # Associations
  has_many :appointments
  has_many :conversations
  has_many :calls
  has_many :messages


  def total_spending
    self.conversations.sum(:billed_amount)
  end

  # in seconds
  def total_session_duration
    total_duration = 0
    self.conversations.map{|con| total_duration += con.duration }
    total_duration
  end

  # in seconds
  def total_paid_duration
    total_duration = 0
    self.conversations.map{|con| total_duration += con.billed_time }
    total_duration
  end

  def has_payment_info?
    !self.card_detail.blank?
  end

end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < ApplicationController

  before_filter :authenticate_admin

  def index
    @users  = User.get_clients
  end

  def new
    @user = Client.new(:user_type =>User::CLIENT_TYPE)
  end

  def create
    @user = Client.new(params[:client])
    if @user.save
      redirect_to admin_clients_path, :notice =>"Client Account Created!"
    else
      render :action =>:new
    end
  end

  def edit
    begin
      @user = Client.find params[:id]
    rescue
      redirect_to admin_clients_path, :notice =>"No Client Found!"
    end
  end

  def update
    @user = Client.find params[:id]
    params.delete(:password) if params[:password].blank?
    if @user.udpate_attributes(params[:client])
      redirect_to admin_clients_path, :notice =>"Client Account Updated!"
    else
      render :action =>:edit
    end
  end

  def destroy
    begin
      @user = Client.find params[:id]
    rescue
      redirect_to admin_clients_path, :notice =>"No Account Found!"
    end
    @user.destroy
    redirect_to admin_clients_path, :notice =>"Account Removed Successfully!"
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def new
    
    # this is how we redirect users on login
    if params[:return_path].present?
      session[:return_to] = params[:return_path]
    end

    # Empy return_to if user came from homepage
    if request.referer == root_url
      session[:return_to] = nil 
    end

    # set up our client
    @client = Client.new

  end

  def create
    @client = Client.new(params[:client])

    if @client.save
      UserMailer.notify_client_signup(@client).deliver
      log_in_user!(@client)
      return redirect_on_login
    else
      return render(:action => :new)
    end
  end

  # method to redirect a user after he logs in
  def redirect_on_login
    # always return to return_to if it's set
    if session[:return_to].present?
      return redirect_to(session.delete(:return_to))
    end
    # default to redirecting to lawyers path
    return redirect_to(lawyers_path)
  end

end

app/views/admin/clients/_form.html.erb
<% errors = @user.errors %>
<%= form_for @user, :url =>admin_clients_path do |f| %>
  <% if @user.errors.size > 0 %>
    <div style="border: 1px solid red;padding: 5px;margin: 10px 10px 20px 100px;width: 500px;">
      The following errors prevented from creating account <br/>
      <ul>
        <% errors.full_messages.each{|error| %>
          <li><%= error %></li>
        <% } %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_type, :value =>@user[:user_type] %>

  <div class="f_label"> First Name : </div>
  <%= f.text_field :first_name %> <br/>
  <div class="f_label"> Last Name : </div>
  <%= f.text_field :last_name %> <br/>

  <div class="f_label">Email:</div>
  <%= f.text_field :email %><br/>

  <div class="f_label">Password:</div>
  <%= f.password_field :password %><br/>

  <div style="margin: 10px 10px 10px 270px;">
    <%= f.submit @user.new_record? ? 'Create Client Account' : 'Update Client Account' %>
    &nbsp; &nbsp; or &nbsp; <%= link_to "Cancel", root_path %>
  </div>
<% end %>

app/views/admin/clients/edit.html.erb
Updating Client Account <span style="float: right;"> <%= link_to "List of Clients", admin_clients_path %> </span> <hr/>

app/views/admin/clients/index.html.erb
<div style="font-size:1.5em;">
List of Clients <span style="float: right;"> <%= link_to 'Add New Client', new_admin_client_path %> </span> <hr/>

<table>
  <thead>
    <tr>
      <td>Name</td> <td>Email</td><td></td>
    </tr>
  </thead>
  <tbody>
    <% @users.each{|user|  %>
      <tr>
        <td> <%= link_to user.full_name, user_path(user), :target =>'_blank' %> </td>
        <td> <%= user.email %> </td>
        <td>
          <%= link_to "Edit Account", edit_user_path(user.id) %> &nbsp;&nbsp;|
          <%= link_to "Remove Account", admin_client_path(user), :method =>:delete, :confirm =>"Are you sure?" %>
        </td>
      </tr>
    <% } %>
  </tbody>
</table>
</div>

app/views/admin/clients/new.html.erb
Creating New Client Account <span style="float: right;"> <%= link_to "List of Clients", admin_clients_path %> </span> <hr/>
<%= render :partial =>'form' %>