config/routes.rb
Lawdingo::Application.routes.draw do
  match 'sitemap.xml' => 'sitemaps#sitemap'

  resources :appointments, :only => [:create]

  resources :clients, :only => [:new, :create]

  namespace :framey do
    resources :videos
  end
  post "framey/callback" => "framey/videos#callback"

  resources :lawyers, :only => [:new, :create]
  match '/apply' => "lawyers#new", :as => :new_lawyer

  resources :questions
  resources :reviews
  resources :schools
  resources :inquiries, only: :show
  resources :bids, only: :create
  get "password_resets/new"

  match 'attorneys/:id/call-payment' => 'attorneys#call_payment', 
    as: :call_payment
  match 'attorneys/:id/*slug' => 'attorneys#show', as: :attorney
  match '/paid' => "stripe#subscribe_lawyer", :as => :subscribe_lawyer
  
  resources :users do
    resources :daily_hours, :only => [:index] do
      collection do
        put "update"
      end
    end
    
    resources :offerings, shallow: true

    put 'image_upload'
    get 'chat_session'
    get 'onlinestatus'
  end

  resources :sessions
  resources :password_resets
  resources :conversations do
    get 'review'
    get 'summary'
  end
  match 'conversations/:conversation_id/summary(/:form)' => "conversations#summary", as: :conversation_summary

  namespace :admin do
    resources :questions, only: [:index, :show] do
      post "send_inquiry", on: :collection
    end
    resources :clients
    resources :lawyers do
      get 'account_approval'
      get 'hm_image'
    end
    resources :clsessions
    resources :pages
    resources :homepage_images
    resources :practice_areas
  end

  match 'modparam' =>'users#update_parameter', :as =>:update_parameter
  match "/users/create_lawyer_request", to: "users#create_lawyer_request", as: :create_lawyer_request
  match '/user/sessions/:user_id' =>"users#session_history", :as =>:user_session_history
  match '/users/:user_id/daily_hours' =>"users#daily_hours", :as =>:user_daily_hours
  match '/users/:user_id' =>"users#account_information", :as =>:user_account_information
  match '/about' =>"pages#show", :name =>'about', :as =>:about_page
  match '/about_attorneys' =>"pages#about_attorneys", :name =>'about_attorneys', :as =>:about_attorneys
  match '/terms' =>"pages#terms_of_use", :name =>'terms', :as =>:terms_page
  match '/pricing_process' =>"pages#pricing_process", :name =>'pricing_process', :as =>:pricing_process
  match '/pricing_process_activation' =>"pages#pricing_process_activation", :name =>'pricing_process_activation', :as =>:pricing_process_activation
  match '/process_signup' =>"pages#process_signup", :name =>'process_signup', :as =>:process_signup
  
  match '/login' => "sessions#new", :as => :login
  match '/logout' => "sessions#destroy", :as => :logout
  match '/details' => 'users#payment_info', :as => :card_detail
  match '/welcome' => 'users#welcome_lawyer', :as => :welcome
  match '/Register' => 'users#register_for_videochat', :as => :register_videochat
  match '/find_friend' => 'users#find_remote_user_for_videochat', :as => :find_remote_user
  match '/UpdateBusyStatus' => 'users#update_busy_status', :as => :UpdateBusyStatus
  match '/ScheduleSession' => 'users#send_email_to_lawyer', :as => :schedule_session
  match '/UpdateOnlineStatus' => 'users#update_online_status', :as => :UpdateOnlineStatus
  match '/twilio/phonecall' => 'users#start_phone_call', :as => :phonecall
  match '/twilio/createcall' => 'users#create_phone_call', :as => :create_call
  match '/twilio/endcall' => 'users#end_phone_call', :as => :endcall
  match '/twilio/voice' => 'twilio#twilio_return_voice', :as => :twilio_voice
  match '/twilio/process_gather' => 'twilio#process_gather', :as => :process_gather
  match '/twilio/fallback' => 'twilio#fallback', :as => :twilio_fallback
  match '/twilio/callback' => 'twilio#callbackstatus', :as => :twilio_callback
  match '/twilio/dial_callback' => 'twilio#dial_callback', :as =>:dial_callback
  match '/search' => 'users#search'
  match '/search/populate_specialities' => 'search#populate_specialities'
  match '/search/populate_specialities_next' => 'search#populate_specialities_next'
  match '/search/filter_results' => 'search#filter_results'
  match '/search/carsousel_images' =>'search#get_homepage_lawyers'
  match '/updatePaymentInfo' => 'users#update_payment_info'
  match '/CheckPaymentInfo' => 'users#has_payment_info'
  match '/CheckCallStatus' => 'users#check_call_status'
  match '/UpdateCallStatus' => 'users#update_call_status'

  match '/admin' =>"users#show", :as =>:admin_home
  
  match '/lawyers/:service_type(/:state)' => 'users#home'
  match '/lawyers/:service_type/:state(/:practice_area)' => 'users#home'
  match '/lawyers/:service_type/:state/:practice_area(/:practice_subarea)' => 'users#home'
  match '/auto-detect/detect-state' => 'users#detect_state'
  match '/lawyers' => 'users#home'
  match '/learnmore' => 'users#learnmore'
  root :to => 'users#landing_page'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

  match '/LoginByApp' => 'sessions#login_by_app'
  match '/UpdateOnlineByApp' => 'sessions#set_status_by_app'
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :client
  belongs_to :lawyer
  has_many :reviews
  has_one :call

  after_create :process_payment

  def self.create_conversation input_params
    client_id       = input_params[:client_id]
    lawyer_id       = input_params[:lawyer_id]
    start_date      = input_params[:start_date]
    end_date        = input_params[:end_date]
    consultation_type = input_params[:consultation_type]
    billable_time   = input_params[:billable_time] || "0"
    lawdingo_charge = AppParameter.service_charge_value

    begin
      lawyer = Lawyer.find(lawyer_id)
    rescue
      logger.info("No Lawyer found")
      lawyer = nil
    end

    if lawyer
      billing_rate  = lawyer.rate
      # calculate billing amount
      billed_amount = billable_time.to_f * (billing_rate + lawdingo_charge)

      conversation = self.create(:client_id =>client_id, :lawyer_id =>lawyer_id, :lawyer_rate =>billing_rate,
        :start_date =>start_date, :end_date =>end_date,:billable_time =>billable_time,:consultation_type => consultation_type,
        :lawdingo_charge =>lawdingo_charge, :billed_amount =>billed_amount, :paid_to_lawyer =>false )
  else
      conversation = nil
    end
    conversation
  end

  def lawyer_name
    lawyer = self.lawyer
    full_name = "#{lawyer.first_name} #{lawyer.last_name}"
    lawyer ? full_name : "-"
  end

  def client_name
    client = self.client
    full_name = "#{client.first_name} #{client.last_name}"
    client ? full_name : "-"
  end

  # in minute
  def duration
    self.end_date - self.start_date
  end

  def lawyer_earning
    self.lawyer_rate * self.billable_time
  end

  # in seconds
  def billed_time
    self.billable_time * 60
  end

  #--------------- Payment Part ---------------------#
  def process_payment
    begin
      user = User.find(self.client_id)
    rescue
      user = nil
    end
    if user
      if self.billable_time > 0
        payment_obj = self.class.process_card user.get_stripe_customer_id, self.id, self.billed_amount
      end
      # change payment status
      self.update_attributes(:has_been_charged => true, :payment_params =>payment_obj.to_json) if payment_obj
      UserMailer.session_notification(self).deliver
    end
  end

  # actual process for payment
  def self.process_card customer_id, conversation_id, billed_amount
    begin
      # create the charge on Stripe's servers - this will charge the user's card
      charge = Stripe::Charge.create(
            :amount => (billed_amount * 100).to_i, # amount in cents
            :currency => "usd",
            :customer => customer_id
        )
    rescue Exception =>exp
      charge = nil
      logger.error("Unable to charge conversation with id: #{conversation_id}\n" + exp.message)
    end
    charge
  end

  #--------------------------------------------------#
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate, :except => [:create]
  protect_from_forgery :except =>[:create]
#  skip_before_filter :protect_from_frogery, :only =>[:create]

  def index
    @conversations = current_user.conversations
  end

  def new
    conversation = Conversation.create_conversation(params[:conversation])
    redirect_to conversation_summary_path(conversation)
  end

  # flash application calls this action
  # after completion it returns 0(in case of failure)
  # or
  # the id of the newly created conversation
  # then the flash redirects to the review page for this conversation
  def create
    lawyer = User.find(params[:lawyer_id])
    lawyer.update_attribute(:is_busy, false)
#    if params.has_key?("state")
#      params.update({"consultation_type" => "video"})
#    else
#      params.update({"consultation_type" => ""})
#    end
    params.update({"consultation_type" => "video"})
    conversation = Conversation.create_conversation(params)
    if current_user && current_user.is_client?
      redirect_to conversation_summary_path(conversation)
    else
      redirect_to users_path(:t=>'l')
    end
#    render :text => conversation ? conversation.id.to_s : "0"
  end

  def review
    begin
      @conversation = Conversation.find params[:conversation_id]
    rescue
      @conversation = nil
    end
  end

  def summary
    @conversation = Conversation.find(params[:conversation_id])
    @lawyer = @conversation.lawyer
    @review = @conversation.reviews.new
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def conversation_summary_form
    if params[:form].present?
      form = params[:form].to_s
    else
      form = "review"
    end

    if form == "review"
      "reviews/form"
    elsif form == "report"
      "no_answer"
    end
  end
end

app/views/conversations/_no_answer.html.erb
<h3>No answer</h3>
<p>Hm... Looks like <%= @conversation.lawyer.full_name %> isn't actually available right now.</p>
<p>If you write <%= @conversation.lawyer.first_name %> a note about what you wanted to talk about, <%= @conversation.lawyer.first_name %> will be sure to get back on you.</p>
<div class="input text"><%= text_area_tag :message, "", style: "width: 400px; height: 100px;" %></div>
<%= hidden_field_tag :lawyer_id, @conversation.lawyer.id %>
<%= submit_tag "Leave message", id: "no_answer_message_submit", class: "button", style: "margin-top: 0.5em" %>
<p>Or <%= link_to "find another lawyer", lawyers_path, style: "display: inline;" %>.</p>

app/views/conversations/index.html.haml
.profile.summary_of_sessions
  - if current_user.is_lawyer?
    .left_menu.same_height
      - act = action_name.to_sym
      - contr = controller_name.to_sym
      %h2= link_to_unless_current "Profile info", user_path(@user, :t => User::ACCOUNT_TAB)
      %ul
        %li.acc_info
          %span= link_to "Account information", user_path(@user, :t => User::ACCOUNT_TAB) 
        %li.price_offers
          %span= link_to "Fixed-price offers", user_offerings_path(@user) 
        %li.availability
          %span= link_to "Set availability", user_daily_hours_path(@user) 
        %li.video
          %span= link_to "Intro video", framey_videos_path
        %li.view_profile
          %span= link_to "View your profile", attorney_path(@user, slug: @user.slug), :target => 'blank'
      %h2= link_to "Summary of sessions", user_path(@user, :t => User::SESSION_TAB), :class => (act == :index && contr == :conversations) ? 'active' : ''
    
  .profile-block.same_height
    - if current_user.is_lawyer?
      - if @conversations.size.zero?
        %h2 You haven’t had any legal sessions yet.
      - else
        %h2 Your summary of earnings and sessions:
        %table.summary
          %thead{:style => "font-weight:bold;"}
            %tr
              %td Client Name
              %td Session Start
              %td Duration of Session
              %td Paid Duration
              %td Rate
              %td.last Amount Earned
          %tbody
            - @conversations.each do |con|
              %tr{:class => cycle("white", "gray")}
                %td
                  = con.client_name
                %td
                  = con.start_date
                %td
                  = seconds_in_string con.duration
                %td
                  = seconds_in_string con.billed_time
                %td
                  = number_to_currency con.lawyer_rate
                  \/min
                %td.last
                  = number_to_currency con.lawyer_earning
            - user = current_user
            %tr.total.gray
              %td
                = pluralize @conversations.map {|c| c.client_id}.uniq.count, "Client", "Clients"
              %td
                = @conversations.size
                Sessions
              %td
                = seconds_in_string user.total_session_duration
              %td
                = seconds_in_string user.total_paid_duration
              - avg_rate = user.total_earning == 0? 0 : (user.total_earning/(user.total_paid_duration.to_f/60))
              %td
                = number_to_currency avg_rate
                \/min
              %td.last
                = number_to_currency user.total_earning.to_i
        / p>Checks are mailed at the end of the each month. Would you like it sooner? Just email to <a href="payments@lawdingo.com">payments@lawdingo.com</a>.</p
        %p
          Payments are made at the end of the month. Prefer a check? Want it sooner? Email
          %a{:href => "mailto:payments@lawdingo.com"} payments@lawdingo.com
          with any requests.
    - else
      %table.summary
        %thead{:style => "font-weight:bold;"}
          %tr
            %td Lawyer Name
            %td Session Start
            %td Duration of Session
            %td Paid Duration
            %td Rate
            %td Lawdingo Fee
            %td Amount Billed
        %tbody
          - @conversations.each do |con|
            %tr
              %td
                = con.lawyer_name
              %td
                = con.start_date
              %td
                = seconds_in_string con.duration
              %td
                = seconds_in_string con.billed_time
              %td
                = number_to_currency con.lawyer_rate
                \/min
              %td
                = number_to_currency con.lawdingo_charge
              %td
                = number_to_currency con.billed_amount
          - user = current_user
          %tr.total
            %td= pluralize @conversations.map{|c| c.lawyer_id}.uniq.count, "Lawyer", "Lawyers"
            %td
              = @conversations.size
              Sessions
            %td
              = seconds_in_string user.total_session_duration
            %td
              = seconds_in_string user.total_paid_duration
            - avg_rate = user.total_spending == 0? 0 : (user.total_spending/(user.total_paid_duration.to_f/60))
            %td
              = number_to_currency avg_rate
              &nbsp; min
            %td= number_to_currency @conversations.map{|c| c.lawdingo_charge}.sum
            %td= number_to_currency user.total_spending.to_i

app/views/conversations/review.html.erb
<% if @conversation %>
  Review the session you just had with Attorney <b> <%= @conversation.lawyer.full_name %> </b>





  <br/><%= link_to "Skip Review", conversation_summary_path(@conversation), :title =>'Leave without giving any review!'  %>
<% else %>
  Nothing to show!
<% end %>

app/views/conversations/summary.html.erb
<div id="page">
  <div>
    <div class="inner session-complete">
      <div class="column">
        <h3>Session summary:</h3>
        <ul class="summary-details">
          <li><span class="label">Actual time elapsed:</span> <%= distance_of_time_in_words(@conversation.start_date, @conversation.end_date) %></li>
          <li><span class="label">Billed time elapsed:</span> <%= @conversation.billable_time %> minute(s)</li>
          <li><span class="label">Attorney's rate:</span> <%= number_to_currency @conversation.lawyer_rate %>/minute</li>
          <li><span class="label">Lawdingo's rate:</span> <%= number_to_currency AppParameter.service_charge_value %>/minute</li>
          <li><span class="label">Amount billed:</span> <%= number_to_currency @conversation.billed_amount %></li>
        </ul>

        <% if params[:call_type].present? && params[:call_type] == 'phonecall' %>
          <%= link_to "Restart Session", phonecall_path(:id => @lawyer.id), :title =>"Restart Session", :class =>'button blue' %>
        <% elsif @lawyer.is_online? && !@lawyer.is_busy %>
            <%= link_to "Restart Session", user_chat_session_path(@lawyer), :title =>"Restart Session", :class =>'button blue' %>
        <% end %>

        <ul class="navigation-links">
          <li><%= link_to "<< Go home", root_path %></li>
          <li><%= link_to 'View all my previous sessions >>', user_path(current_user,:t =>'l'), :title => 'View all my previous sessions' %></li>
        </ul>
      </div>

      <div class="column last-child">
        <%= render conversation_summary_form %>
      </div>

      <div class="clear"></div>
    </div>
  </div>
</div>