config/routes.rb
Lawdingo::Application.routes.draw do
  match 'sitemap.xml' => 'sitemaps#sitemap'

  resources :appointments, :only => [:create]

  resources :clients, :only => [:new, :create]

  namespace :framey do
    resources :videos
  end
  post "framey/callback" => "framey/videos#callback"

  resources :lawyers, :only => [:new, :create]
  match '/apply' => "lawyers#new", :as => :new_lawyer

  resources :questions
  resources :reviews
  resources :schools
  resources :inquiries, only: :show
  resources :bids, only: :create
  get "password_resets/new"

  match 'attorneys/:id/call-payment' => 'attorneys#call_payment', 
    as: :call_payment
  match 'attorneys/:id/*slug' => 'attorneys#show', as: :attorney
  match '/paid' => "stripe#subscribe_lawyer", :as => :subscribe_lawyer
  
  resources :users do
    resources :daily_hours, :only => [:index] do
      collection do
        put "update"
      end
    end
    
    resources :offerings, shallow: true

    put 'image_upload'
    get 'chat_session'
    get 'onlinestatus'
  end

  resources :sessions
  resources :password_resets
  resources :conversations do
    get 'review'
    get 'summary'
  end
  match 'conversations/:conversation_id/summary(/:form)' => "conversations#summary", as: :conversation_summary

  namespace :admin do
    resources :questions, only: [:index, :show] do
      post "send_inquiry", on: :collection
    end
    resources :clients
    resources :lawyers do
      get 'account_approval'
      get 'hm_image'
    end
    resources :clsessions
    resources :pages
    resources :homepage_images
    resources :practice_areas
  end

  match 'modparam' =>'users#update_parameter', :as =>:update_parameter
  match "/users/create_lawyer_request", to: "users#create_lawyer_request", as: :create_lawyer_request
  match '/user/sessions/:user_id' =>"users#session_history", :as =>:user_session_history
  match '/users/:user_id/daily_hours' =>"users#daily_hours", :as =>:user_daily_hours
  match '/users/:user_id' =>"users#account_information", :as =>:user_account_information
  match '/about' =>"pages#show", :name =>'about', :as =>:about_page
  match '/about_attorneys' =>"pages#about_attorneys", :name =>'about_attorneys', :as =>:about_attorneys
  match '/terms' =>"pages#terms_of_use", :name =>'terms', :as =>:terms_page
  match '/pricing_process' =>"pages#pricing_process", :name =>'pricing_process', :as =>:pricing_process
  match '/pricing_process_activation' =>"pages#pricing_process_activation", :name =>'pricing_process_activation', :as =>:pricing_process_activation
  match '/process_signup' =>"pages#process_signup", :name =>'process_signup', :as =>:process_signup
  
  match '/login' => "sessions#new", :as => :login
  match '/logout' => "sessions#destroy", :as => :logout
  match '/details' => 'users#payment_info', :as => :card_detail
  match '/welcome' => 'users#welcome_lawyer', :as => :welcome
  match '/Register' => 'users#register_for_videochat', :as => :register_videochat
  match '/find_friend' => 'users#find_remote_user_for_videochat', :as => :find_remote_user
  match '/UpdateBusyStatus' => 'users#update_busy_status', :as => :UpdateBusyStatus
  match '/ScheduleSession' => 'users#send_email_to_lawyer', :as => :schedule_session
  match '/UpdateOnlineStatus' => 'users#update_online_status', :as => :UpdateOnlineStatus
  match '/twilio/phonecall' => 'users#start_phone_call', :as => :phonecall
  match '/twilio/createcall' => 'users#create_phone_call', :as => :create_call
  match '/twilio/endcall' => 'users#end_phone_call', :as => :endcall
  match '/twilio/voice' => 'twilio#twilio_return_voice', :as => :twilio_voice
  match '/twilio/process_gather' => 'twilio#process_gather', :as => :process_gather
  match '/twilio/fallback' => 'twilio#fallback', :as => :twilio_fallback
  match '/twilio/callback' => 'twilio#callbackstatus', :as => :twilio_callback
  match '/twilio/dial_callback' => 'twilio#dial_callback', :as =>:dial_callback
  match '/search' => 'users#search'
  match '/search/populate_specialities' => 'search#populate_specialities'
  match '/search/populate_specialities_next' => 'search#populate_specialities_next'
  match '/search/filter_results' => 'search#filter_results'
  match '/search/carsousel_images' =>'search#get_homepage_lawyers'
  match '/updatePaymentInfo' => 'users#update_payment_info'
  match '/CheckPaymentInfo' => 'users#has_payment_info'
  match '/CheckCallStatus' => 'users#check_call_status'
  match '/UpdateCallStatus' => 'users#update_call_status'

  match '/admin' =>"users#show", :as =>:admin_home
  
  match '/lawyers/:service_type(/:state)' => 'users#home'
  match '/lawyers/:service_type/:state(/:practice_area)' => 'users#home'
  match '/lawyers/:service_type/:state/:practice_area(/:practice_subarea)' => 'users#home'
  match '/auto-detect/detect-state' => 'users#detect_state'
  match '/lawyers' => 'users#home'
  match '/learnmore' => 'users#learnmore'
  root :to => 'users#landing_page'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

  match '/LoginByApp' => 'sessions#login_by_app'
  match '/UpdateOnlineByApp' => 'sessions#set_status_by_app'
end

app/views/admin/_home_page.html.erb
<span style="float: right;"> <%= link_to "Edit Admin Account", edit_user_path(current_user) %></span>

<div style="width: 93%;margin-right: 10px;margin-top: 20px;float: left;">
  <div class="header_mb">
    Application Specific Values
  </div>
  <div class="desc">
    <% AppParameter.all.each{|pa| %>
      <%= pa.name %>
      <input type="text" id="pvalue_<%= pa.id %>" value="<%= pa.value %>" size="78%" />
      <input type="button" value="Save" onclick="$.ajax({
            url: '<%= update_parameter_path %>',
            data: {id:<%= pa.id %>,value: $('input#pvalue_<%= pa.id %>').val()},
            success : function(text){alert(text);}
          });" />
      <br/><br/>
    <% } %>
  </div>
</div>

<div style="width: 30%;margin-right: 10px;margin-top: 20px;float: left;">
  <div class="header_mb">
    Client Management
  </div>
  <div class="desc">
    <%= link_to "Client List", admin_clients_path %><br />
    <%= link_to "Add New Client", new_admin_client_path %><br />
    <%= link_to "Clients questions", admin_questions_path %>
  </div>
</div>

<div style="width: 30%;margin-right: 10px;margin-top: 20px;float: left;">
  <div class="header_mb">
    Lawyer Management
  </div>
  <div class="desc">
    <%= link_to "Lawyer List", admin_lawyers_path %><br/>
    <%= link_to "Add New Laywer", new_admin_lawyer_path %>
  </div>
</div>

<div style="width: 30%;margin-right: 10px;margin-top: 20px;float: left;">
  <div class="header_mb">
    Practice Area Management
  </div>
  <div class="desc">
    <%= link_to "Practice Areas List", admin_practice_areas_path %><br/>
    <%= link_to "Add New Practice Area", new_admin_practice_area_path %>
  </div>
</div>

<div style="width: 30%;margin-right: 10px;margin-top: 20px;float: left;">
  <div class="header_mb">
    Lawyer Homepage Image Management
  </div>
  <div class="desc">
    <%= link_to "Lawyer Homepage Image List", admin_homepage_images_path %><br/>
  </div>
</div>

<div style="width: 30%;margin-right: 10px;margin-top: 20px;float: left;">
  <div class="header_mb">
    Client-Lawyer Sessions
  </div>
  <div class="desc">
    <%= link_to "Recent Sessions", admin_clsessions_path %><br/>
  </div>
</div>
<div style="width: 30%;margin-right: 10px;margin-top: 20px;float: left;">
  <div class="header_mb">
    Page Management
  </div>
  <div class="desc">
    <%= link_to "Pages", admin_pages_path %><br/>
    <%= link_to "Add New Page", new_admin_page_path %><br/>
  </div>
</div>